###
GET http://localhost:5000/api/


###
POST http://localhost:5000/workout/
Content-Type: application/json
{
  "title": "test-name",
  "body": "test-body",
}


###
POST http://localhost:5000/workout/
{
  "name": "test",
  "description": "test",
  "exercises": [
      {
          "name": "test",
          "description": "test",
          "sets": [
              {
                  "reps": 10,
                  "weight": 10
              }
          ]
      }
  ]
}